[[constraint]]
  name = "github.com/goadesign/goa"
	version = "v1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/tylerb/graceful"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"
